
name: 'libGDX Android upload'
description: 'libGDX: Build Android app and upload to Google Play Store'
author: 'Simon Dalvai @dulvui'
branding:
  color: green
  icon: upload-cloud

inputs:
  service-account-json:
    description: 'Path to a valid Google service-account.json'
    required: false
    default: service-account.json
  package-name:
    description: 'Android package name'
    required: true
  release-track:
    description: 'Release track: production, beta, alpha, internalsharing, internal'
    required: false
    default: 'internal'
  
runs:
  using: "composite"
  steps:
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 11

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Build the libGDX application
      shell: bash
      run: ./gradlew android:bundleRelease

    - name: Publish to Play Store
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJson: ${{ inputs.service-account-json }}
        packageName: ${{ inputs.package-name }}
        releaseFiles: android/build/outputs/aab/release/*.aab
        track: ${{ inputs.release-track }}
        status: completed